# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/proxy/proxy.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/proxy/proxy.proto\"\xa7\x01\n\x0cProxyMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x63reate_time\x18\x02 \x01(\x05\x12)\n\x06status\x18\x03 \x01(\x0e\x32\x19.ProxyMessage.ProxyStatus\x12\x10\n\x08use_time\x18\x04 \x01(\x05\x12\x0b\n\x03url\x18\x05 \x01(\t\",\n\x0bProxyStatus\x12\x08\n\x04USED\x10\x00\x12\x08\n\x04INIT\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.proxy.proxy_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROXYMESSAGE._serialized_start=28
  _PROXYMESSAGE._serialized_end=195
  _PROXYMESSAGE_PROXYSTATUS._serialized_start=151
  _PROXYMESSAGE_PROXYSTATUS._serialized_end=195
# @@protoc_insertion_point(module_scope)
