# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/spider/parse_setting.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n proto/spider/parse_setting.proto\"\xdf\x01\n\x13ParseSettingMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x30\n\x06status\x18\x02 \x01(\x0e\x32 .ParseSettingMessage.ParseStatus\x12\x13\n\x0bparse_rules\x18\x03 \x01(\t\x12\x12\n\nparse_time\x18\x04 \x01(\x05\x12\x17\n\x0fnext_page_rules\x18\x06 \x01(\t\x12\x0c\n\x04step\x18\x07 \x01(\x05\x12\x12\n\ntotal_step\x18\t \x01(\x05\"&\n\x0bParseStatus\x12\x0b\n\x07STARTED\x10\x00\x12\n\n\x06\x46INISH\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.spider.parse_setting_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PARSESETTINGMESSAGE._serialized_start=37
  _PARSESETTINGMESSAGE._serialized_end=260
  _PARSESETTINGMESSAGE_PARSESTATUS._serialized_start=222
  _PARSESETTINGMESSAGE_PARSESTATUS._serialized_end=260
# @@protoc_insertion_point(module_scope)
