# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/spider/spider.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/spider/spider.proto\"\xcd\x02\n\rSpiderMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\ntarget_url\x18\x02 \x01(\t\x12\x18\n\x10parse_setting_id\x18\x03 \x01(\t\x12\x13\n\x0b\x63reate_time\x18\x04 \x01(\x03\x12+\n\x06status\x18\x05 \x01(\x0e\x32\x1b.SpiderMessage.SpiderStatus\x12\x12\n\nretry_time\x18\x06 \x01(\x03\x12\x13\n\x0b\x66inish_time\x18\x07 \x01(\x03\x12\x34\n\x0erequest_method\x18\x08 \x01(\x0e\x32\x1c.SpiderMessage.RequestMethod\x12\x0c\n\x04step\x18\t \x01(\x05\"/\n\x0cSpiderStatus\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05RETRY\x10\x01\x12\n\n\x06\x46INISH\x10\x02\"\"\n\rRequestMethod\x12\x07\n\x03GET\x10\x00\x12\x08\n\x04POST\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.spider.spider_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPIDERMESSAGE._serialized_start=30
  _SPIDERMESSAGE._serialized_end=363
  _SPIDERMESSAGE_SPIDERSTATUS._serialized_start=280
  _SPIDERMESSAGE_SPIDERSTATUS._serialized_end=327
  _SPIDERMESSAGE_REQUESTMETHOD._serialized_start=329
  _SPIDERMESSAGE_REQUESTMETHOD._serialized_end=363
# @@protoc_insertion_point(module_scope)
