# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spider_common/proto/cookie/cookie.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'spider_common/proto/cookie/cookie.proto\"\xaa\x02\n\rCookieMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x63reate_time\x18\x02 \x01(\x05\x12+\n\x06status\x18\x03 \x01(\x0e\x32\x1b.CookieMessage.CookieStatus\x12\x13\n\x0brequest_url\x18\x04 \x01(\t\x12\x10\n\x08response\x18\x05 \x01(\t\x12\x31\n\ncookie_map\x18\x06 \x03(\x0b\x32\x1d.CookieMessage.CookieMapEntry\x12\x10\n\x08use_time\x18\x07 \x01(\x05\x1a\x30\n\x0e\x43ookieMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"-\n\x0c\x43ookieStatus\x12\x08\n\x04USED\x10\x00\x12\x08\n\x04INIT\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spider_common.proto.cookie.cookie_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COOKIEMESSAGE_COOKIEMAPENTRY._options = None
  _COOKIEMESSAGE_COOKIEMAPENTRY._serialized_options = b'8\001'
  _COOKIEMESSAGE._serialized_start=44
  _COOKIEMESSAGE._serialized_end=342
  _COOKIEMESSAGE_COOKIEMAPENTRY._serialized_start=247
  _COOKIEMESSAGE_COOKIEMAPENTRY._serialized_end=295
  _COOKIEMESSAGE_COOKIESTATUS._serialized_start=297
  _COOKIEMESSAGE_COOKIESTATUS._serialized_end=342
# @@protoc_insertion_point(module_scope)
