# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/spider.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/spider.proto\"\xdd\x01\n\rSpiderMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x63reate_time\x18\x02 \x01(\t\x12+\n\x06status\x18\x03 \x01(\x0e\x32\x1b.SpiderMessage.SpiderStatus\x12\x13\n\x0brequest_url\x18\x04 \x01(\t\x12\x10\n\x08response\x18\x05 \x01(\t\x12\x12\n\nretry_time\x18\x06 \x01(\t\x12\x12\n\nparse_time\x18\x07 \x01(\t\"/\n\x0cSpiderStatus\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05RETRY\x10\x01\x12\n\n\x06PARSED\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.spider_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPIDERMESSAGE._serialized_start=23
  _SPIDERMESSAGE._serialized_end=244
  _SPIDERMESSAGE_SPIDERSTATUS._serialized_start=197
  _SPIDERMESSAGE_SPIDERSTATUS._serialized_end=244
# @@protoc_insertion_point(module_scope)
